### ISSUE TITLE
publisher-1.8.0-Alpha.9\class\Form\ThemeTabForm.php LINE 23

### ISSUE THREAD

**Issue by CHCCD** [mambax7/publisher#18]
publisher-1.8.0-Alpha.9\class\Form\ThemeTabForm.php LINE 23
require_once \dirname(__DIR__) . '/include/common.php';
Fix:
require_once \dirname(dirname(__DIR__)) . '/include/common.php';

**Comment by mambax7** [comment]
Thanks for reporting, it's fixed now
