### ISSUE TITLE
Error in the block from date to date

### ISSUE THREAD

**Issue by aerograf** [mambax7/publisher#8]
The block displays:
`Articles published between foroov}i}u{}eti}ymuimm(/m/ooo/y/) and 0 `

**Comment by mambax7** [comment]
If I remember correctly, you need to have more than 1 articles, and you need to set in the Block Editor. 
See if it works, and if not, I'll take a look...

**Comment by mambax7** [comment]
Just tested locally here, and it works fine. I hope, there is nothing related to a date in a different format...

**Comment by aerograf** [comment]
It does not depend on the set date and the chosen language.
`foroov}i}u{}e�ti}ymuimm(/m/oo�o/y/)`
under any conditions.
https://xoops.shmel.org/modules/publisher/

**Comment by mambax7** [comment]
This should fix it now
https://github.com/mambax7/publisher/commit/2a41a26ee07f6ef5aef5e42dd50cf047ad77aae5

**Comment by aerograf** [comment]
Now installation error:
`ERROR: Failed to add block Articles from date to date in the database! Database Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'oooo/) .', 'Articles from date to date','Articles from date to date', '', 0, 0' at line 1`

**Comment by mambax7** [comment]
Ouch!  That's not good. I'll check on it ...

**Comment by mambax7** [comment]
I hope, this will now fix it: https://github.com/XoopsModules25x/publisher/pull/108

**Comment by aerograf** [comment]
Yes. It worked. I will test further. Thank.
